from enum import IntEnum

class MetagameEventType(IntEnum):
    # VS Triggered
    INDAR_ENLIGHTENMENT = 148
    HOSSIN_ENLIGHTENMENT = 154
    AMERISH_ENLIGHTENMENT = 157
    ESAMIR_ENLIGHTENMENT = 151
    OSHUR_ENGLIGHTENMENT = 224

    # NC Triggered
    INDAR_LIBERATION = 149
    HOSSIN_LIBERATION = 155
    AMERISH_LIBERATION = 158
    ESAMIR_LIBERATION = 152
    OSHUR_LIBERATION = 222

    # TR Triggered
    INDAR_SUPERIORITY = 147
    HOSSIN_SUPERIORITY = 153
    AMERISH_SUPERIORITY = 156
    ESAMIR_SUPERIORITY = 150
    OSHUR_SUPERIORITY = 223

    # Current Generation Unstable Meltdowns
    NC_INDAR_UNSTABLE_MELTDOWN = 179
    NC_HOSSIN_UNSTABLE_MELTDOWN = 177
    NC_AMERISH_UNSTABLE_MELTDOWN = 178
    NC_ESAMIR_UNSTABLE_MELTDOWN = 176

    VS_INDAR_UNSTABLE_MELTDOWN = 189
    VS_HOSSIN_UNSTABLE_MELTDOWN = 187
    VS_AMERISH_UNSTABLE_MELTDOWN = 188
    VS_ESAMIR_UNSTABLE_MELTDOWN = 186

    TR_INDAR_UNSTABLE_MELTDOWN = 193
    TR_HOSSIN_UNSTABLE_MELTDOWN = 191
    TR_AMERISH_UNSTABLE_MELTDOWN = 192
    TR_ESAMIR_UNSTABLE_MELTDOWN = 190

    # High pop alerts
    AMERISH_HIGH_POP_CONQUEST = 211
    ESAMIR_HIGH_POP_CONQUEST = 212
    HOSSIN_HIGH_POP_CONQUEST = 213
    INDAR_HIGH_POP_CONQUEST = 214
    OSHUR_HIGH_POP_CONQUEST = 226

    # Outfit Wars Alerts
    NEXUS_OUTFIT_WAR = 227
    NEXUS_OUTFIT_WAR_PREP = 234
